/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by tools/generate_lifecycle_header.py; do not edit. */
#ifndef _G6TS_LIFECYCLE_PROFILE_H
#define _G6TS_LIFECYCLE_PROFILE_H

#define G6TS_WINDOWS_UNCLASSIFIED 4U
#define G6TS_WINDOWS_HISTORY_CAPACITY 10U
#define G6TS_WINDOWS_SCORE_SHIFT 24U
#define G6TS_WINDOWS_RUNTIME_OFFSET_Q24 -177430463LL
#define G6TS_WINDOWS_SCORE3_PRIMARY_Q24 838860800LL
#define G6TS_WINDOWS_SCORE3_SINGLE_Q24 335544320LL
#define G6TS_WINDOWS_ASSIGN_X_SCALE_Q24 68082944U
#define G6TS_WINDOWS_ASSIGN_Y_SCALE_Q24 67306464U
#define G6TS_WINDOWS_ASSIGN_RADIUS 5U

struct g6ts_transition_rule {
	s32 history_margins[G6TS_CLASS_COUNT];
	s32 current_margins[G6TS_CLASS_COUNT];
	s16 absolute_minimum;
	s8 context_score_bias;
	u8 history_depth;
	u8 initial_age_limit;
	u8 context_allowed;
	u8 context_extra_history;
};

static const u16 g6ts_class_point_minimums[G6TS_CLASS_COUNT] = { 0, 6, 4, 4 };
static const u16 g6ts_class_point_maximums[G6TS_CLASS_COUNT] = { 20, 9999, 50, 100 };

static const struct g6ts_transition_rule g6ts_transition_rules[] = {
	/* 0 -> 0 */
	{
		.history_margins = { 0, 0, 0, 0 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = 0,
		.context_score_bias = 2,
		.history_depth = 0,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 0 -> 1 */
	{
		.history_margins = { 20, 0, 10, 30 },
		.current_margins = { 100, 0, 10, 30 },
		.absolute_minimum = -500,
		.context_score_bias = 2,
		.history_depth = 5,
		.initial_age_limit = 3,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 0 -> 2 */
	{
		.history_margins = { 2, 30, 0, 30 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = -25,
		.context_score_bias = 2,
		.history_depth = 2,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 0 -> 3 */
	{
		.history_margins = { 200, 15, 7, 0 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = -45,
		.context_score_bias = 2,
		.history_depth = 1,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 1 -> 0 */
	{
		.history_margins = { 0, 5, 5, 40 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = -2,
		.context_score_bias = 2,
		.history_depth = 8,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 1 -> 1 */
	{
		.history_margins = { 0, 0, 0, 0 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = 0,
		.context_score_bias = 2,
		.history_depth = 0,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 1 -> 2 */
	{
		.history_margins = { 1, 30, 0, 40 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = -25,
		.context_score_bias = 2,
		.history_depth = 4,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 1 -> 3 */
	{
		.history_margins = { 30, 30, 30, 0 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = -20,
		.context_score_bias = 2,
		.history_depth = 30,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 2 -> 0 */
	{
		.history_margins = { 0, 15, 1, 15 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = -25,
		.context_score_bias = 2,
		.history_depth = 2,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 2 -> 1 */
	{
		.history_margins = { 40, 0, 80, 30 },
		.current_margins = { 100, 0, 80, 80 },
		.absolute_minimum = -500,
		.context_score_bias = 2,
		.history_depth = 5,
		.initial_age_limit = 3,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 2 -> 2 */
	{
		.history_margins = { 0, 0, 0, 0 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = 0,
		.context_score_bias = 2,
		.history_depth = 0,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 2 -> 3 */
	{
		.history_margins = { 50, 10, 30, 0 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = -15,
		.context_score_bias = 2,
		.history_depth = 4,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 3 -> 0 */
	{
		.history_margins = { 0, 15, 1, 15 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = -25,
		.context_score_bias = 2,
		.history_depth = 1,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 3 -> 1 */
	{
		.history_margins = { 20, 0, 40, 100 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = -40,
		.context_score_bias = 2,
		.history_depth = 5,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 3 -> 2 */
	{
		.history_margins = { 2, 12, 0, 30 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = -25,
		.context_score_bias = 2,
		.history_depth = 3,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 3 -> 3 */
	{
		.history_margins = { 0, 0, 0, 0 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = 0,
		.context_score_bias = 2,
		.history_depth = 0,
		.initial_age_limit = 0,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
	/* 4 -> 0 */
	{
		.history_margins = { 0, 6, 1, 30 },
		.current_margins = { 0, 10, 1, 30 },
		.absolute_minimum = -3,
		.context_score_bias = 0,
		.history_depth = 2,
		.initial_age_limit = 3,
		.context_allowed = 0,
		.context_extra_history = 3,
	},
	/* 4 -> 1 */
	{
		.history_margins = { 22, 0, 15, 15 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = -9999,
		.context_score_bias = 2,
		.history_depth = 2,
		.initial_age_limit = 0,
		.context_allowed = 0,
		.context_extra_history = 0,
	},
	/* 4 -> 2 */
	{
		.history_margins = { 1, 3, 0, 8 },
		.current_margins = { 255, 255, 255, 255 },
		.absolute_minimum = -8,
		.context_score_bias = 2,
		.history_depth = 4,
		.initial_age_limit = 3,
		.context_allowed = 0,
		.context_extra_history = 2,
	},
	/* 4 -> 3 */
	{
		.history_margins = { 100, 7, 8, 0 },
		.current_margins = { 100, 30, 10, 0 },
		.absolute_minimum = -20,
		.context_score_bias = 2,
		.history_depth = 3,
		.initial_age_limit = 3,
		.context_allowed = 1,
		.context_extra_history = 0,
	},
};

#endif /* _G6TS_LIFECYCLE_PROFILE_H */
